services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=flightactivity_db
    networks:
      - default
  web:
    build: .
    environment:
      - DB_USER=postgres
      - DB_PASS=pass
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - default
    volumes:
      - .:/app-dev