services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=flightactivity_db
    volumes:
      - postgres_data_prod:/var/lib/postgresql/

  flightactivity:
    build:
      context: .
      dockerfile: Dockerfile_prod
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    env_file: cert.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /path/to/conf:/etc/nginx/conf.d
      # dont forget to mount certs dir when deploying
volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
