version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=flightactivity_db
    networks:
      - default
  web:
    image: nothardengineer/flightactivity:dev_14-01-2024
#    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - default
    volumes:
      - .:/python-docker